<?php

namespace AppBundle\Repository;

/**
 * ShiporderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShiporderRepository extends \Doctrine\ORM\EntityRepository
{
}
